# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3
        "types": [python]
      - id: isort
        name: isort
        entry: isort
        language: python
        language_version: python3
        "types": [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        language_version: python3
        "types": [python]
        exclude: (?x)^(
          migration_versions/[\w_]*/migrations/[\w_]*\.py
          )$
        args: [--rcfile, setup.cfg]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        language_version: python3
        "types": [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        language_version: python3
        "types": [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        additional_dependencies: []
